init_path : "C:/Users/gustavo/Documents/Data Science/08-GitHub/kaggles/Classification/Titanic"
competition: "titanic"

## Data gathering
data:  
  raw: "data/raw"
  processed: "data/processed"
  feature_eng: "data/feature_eng"
  submission: "data/submission"

reports:  
  figures: "reports/plots"
  tables: "reports/jsonl"
  
pipeline:
  pkl: "pipelines"

single_model:
  pkl: "models/single_model/pkl"
  figures: "models/single_model/plots"
  tables: "models/single_model/tables"
  predicts: "models/single_model/predictions"

