features:
  cat_var:
      - Pclass    
      - Sex
      - Embarked
      - Title
      - Cabin_1p
  num_dis:    
      - SibSp
      - Parch    
      - IsAlone
      - FamilySize      
  num_con:
      - Age
      - Fare

  target: 
      - Survived


